"""Build the whole metrics pack, then print every headline number in one table.

    .venv/bin/python ml/report/generate.py                 # the full pack
    .venv/bin/python ml/report/generate.py --only summary  # just re-read what is on disk

Into ml/artifacts/:

    confusion_matrix.png        ml/eval.py, on the test split
    per_class_table.md          ml/eval.py
    metrics.json                ml/eval.py
    baseline_comparison.md      fine-tune vs the from-scratch CNN
    lab_vs_field.png / .md      ml/report/field_gap.py
    pipeline_scan.md            ml/report/pipeline_run.py — real end-to-end runs
    latency.md                  per-tile ONNX + the measured scan, assembled here
    block_rate.md               ml/report/verifier_eval.py — run that separately
    SUMMARY.md                  the table below

**Nothing here computes a metric.** Every number is produced by the script that owns the
measurement — eval.py owns accuracy, baseline.py owns the comparison prose, export_onnx.py owns
per-tile latency — and this file runs them, reads what they wrote, and lays it out. That is the
whole design: a number can appear on a slide only if some script already wrote it to disk, so
"where did that come from" always has a one-word answer.

`--only summary` deliberately recomputes nothing. It re-reads the artifacts and rebuilds the
table, which is what you want at hour 20 when a chart has been regenerated by hand and the
question is whether the summary still agrees with it.

The adversarial suite is not run from here. It takes a different kind of time, it can fail for
reasons that have nothing to do with the model, and burying it in a pack build is how a red
number goes unnoticed. `ml/report/verifier_eval.py`, on purpose.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

ML_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = ML_DIR.parent
sys.path.insert(0, str(ML_DIR))
sys.path.insert(0, str(Path(__file__).resolve().parent))

ARTIFACTS = ML_DIR / "artifacts"
STEPS = ("eval", "baseline", "field", "pipeline", "latency", "summary")


def read(name: str):
    path = ARTIFACTS / name
    return json.loads(path.read_text()) if path.exists() else None


def step_eval(args) -> None:
    from eval import run_eval

    run_eval(checkpoint=ML_DIR / "checkpoints" / "best.pt", split=args.split,
             batch_size=args.batch_size, num_workers=args.num_workers, device=args.device)


def step_baseline(args) -> None:
    """Re-score the from-scratch CNN and rewrite the comparison, using baseline.py's own writer.

    Evaluation only — this does not retrain. If checkpoints/baseline.pt is missing, the
    comparison is left as it was rather than being written with half its columns empty.
    """
    from baseline import write_comparison
    from eval import run_eval

    checkpoint = ML_DIR / "checkpoints" / "baseline.pt"
    if not checkpoint.exists():
        print(f"skipping baseline: {checkpoint} missing (run ml/baseline.py)")
        return
    metrics = run_eval(checkpoint=checkpoint, split=args.split, batch_size=args.batch_size,
                       num_workers=args.num_workers, device=args.device, tag="baseline")
    write_comparison(metrics, ARTIFACTS / "baseline_comparison.md")
    print(f"wrote {ARTIFACTS}/baseline_comparison.md")


def step_field(args) -> None:
    from field_gap import build

    build(ML_DIR / "checkpoints" / "best.pt", split=args.split, batch_size=args.batch_size,
          num_workers=args.num_workers, device=args.device)


def step_pipeline(args) -> None:
    from pipeline_run import TESTDATA, build

    images = sorted(TESTDATA.glob("field_*.jpg"))
    if not images:
        print(f"skipping pipeline: no field images in {TESTDATA}")
        return
    build(images, [True] + ([False] if args.online else []))


def step_latency(args) -> None:
    """latency.md — the per-tile number and the measured end-to-end scan, in one place.

    They belong together because quoted apart they mislead in opposite directions: 4.9 ms per
    tile sounds like a scan is instant, and a 20-second online run sounds like the model is
    slow, when it is one LLM call.
    """
    latency, scans = read("latency.json"), read("pipeline_scan.json")
    if not latency:
        print("skipping latency: no latency.json (run ml/export_onnx.py)")
        return
    per_tile, conditions = latency["per_tile"], latency.get("conditions", {})
    parts = [
        "# Latency\n",
        "## Per tile — ONNX Runtime, CPU\n",
        f"{conditions.get('provider', 'CPUExecutionProvider')}, batch {conditions.get('batch', 1)}, "
        f"{conditions.get('img_size', 224)}x{conditions.get('img_size', 224)}, "
        f"{per_tile.get('runs', '?')} runs after warm-up.\n",
        "| metric | ms |\n|---|---:|\n"
        + "\n".join(f"| {k} | {per_tile[f'{k}_ms']:.1f} |" for k in ("mean", "median", "p95", "min", "max")),
        f"\nParity with PyTorch: {latency['parity']['argmax_agreement']}/"
        f"{latency['parity']['n_samples']} argmax agree, max |logit diff| "
        f"{latency['parity']['max_abs_logit_diff']:.2e}.\n",
    ]
    if scans:
        offline = [s for s in scans if s["offline"]]
        online = [s for s in scans if not s["offline"]]
        tiles = conditions.get("tiles_per_scan", 40)
        extrapolated = per_tile["mean_ms"] * tiles / 1000
        parts.append("## Per scan — the whole pipeline, measured\n")
        parts.append(
            f"| path | median end-to-end | vision | language |\n|---|---:|---:|---:|\n"
            + "\n".join(
                f"| {name} | {statistics.median(r['total_ms'] for r in rows) / 1000:.2f} s | "
                f"{statistics.median(r['vision_ms'] for r in rows) / 1000:.2f} s | "
                f"{statistics.median(r['language_ms'] for r in rows) / 1000:.2f} s |"
                for name, rows in (("offline (extractive drafter)", offline), ("online (LLM drafting)", online))
                if rows
            )
        )
        if offline:
            measured = statistics.median(r["total_ms"] for r in offline) / 1000
            parts.append(
                f"\n{tiles} tiles x the per-tile mean predicts {extrapolated:.2f} s of inference; "
                f"the measured offline run is **{measured:.2f} s**. The difference is everything "
                "inference is not — decode, tile, green-mask, batch, the second pass over "
                "escalated tiles, DBSCAN, retrieval. Quote the measured number.\n"
            )
        if online:
            parts.append(
                f"\nOn the online path the language column is the run. See pipeline_scan.md for "
                "the per-image breakdown.\n"
            )
    else:
        parts.append(
            "\n_No measured scan on disk — run `ml/report/pipeline_run.py`. Until then the only "
            "honest scan number is per-tile latency times tile count, which counts inference and "
            "nothing else._\n"
        )
    (ARTIFACTS / "latency.md").write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {ARTIFACTS}/latency.md")


# --- the summary ----------------------------------------------------------------------------


def rows_for_summary() -> list[tuple[str, str, str]]:
    """(metric, value, where it came from). A dash means the script that owns it has not run."""
    metrics, baseline = read("metrics.json"), read("metrics_baseline.json")
    field, latency = read("lab_vs_field.json"), read("latency.json")
    scans, blocks = read("pipeline_scan.json"), read("block_rate.json")
    out: list[tuple[str, str, str]] = []

    def add(label: str, value, source: str) -> None:
        out.append((label, "—" if value is None else value, source))

    if metrics:
        add("test accuracy", f"{metrics['accuracy']:.1%}", "metrics.json")
        add("test macro-F1", f"{metrics['macro_f1']:.4f}", "metrics.json")
        add("classes / test images", f"{metrics['n_classes']} / {metrics['n_images']:,}", "metrics.json")
        add("escalated at 0.75", f"{metrics['confidence']['escalation_rate']:.1%}", "metrics.json")
    if metrics and baseline:
        delta = metrics["macro_f1"] - baseline["macro_f1"]
        add("vs from-scratch CNN", f"{delta:+.4f} macro-F1", "baseline_comparison.md")
    if field:
        clean, worst = field["rows"][0], field["rows"][-1]
        add("simulated field accuracy", f"{worst['accuracy']:.1%}  ({worst['accuracy'] - clean['accuracy']:+.1%})",
            "lab_vs_field.md")
        add("escalated, field conditions", f"{worst['escalation_rate']:.1%}", "lab_vs_field.md")
        add("real field photos", "not collected" if not field["real_photos"] else
            f"{worst['accuracy']:.1%}", "demo/field_photos/")
    if latency:
        add("per-tile inference", f"{latency['per_tile']['mean_ms']:.1f} ms CPU", "latency.md")
    if scans:
        offline = [s for s in scans if s["offline"]]
        graded = [s for s in scans if s.get("label_accuracy") is not None]
        if offline:
            add("end-to-end scan, offline", f"{statistics.median(r['total_ms'] for r in offline) / 1000:.2f} s",
                "latency.md")
        online = [s for s in scans if not s["offline"]]
        if online:
            add("end-to-end scan, online", f"{statistics.median(r['total_ms'] for r in online) / 1000:.2f} s",
                "latency.md")
        if graded:
            add("tile accuracy on labelled mosaics",
                f"{statistics.mean(r['label_accuracy'] for r in graded):.1%}", "pipeline_scan.md")
    if blocks:
        s = blocks["summary"]
        landed = s["blocked"] + s["stripped"] + s["leaked"]
        add("adversarial attacks landed", f"{landed} of {s['trials']}", "block_rate.md")
        add("caught by the Verifier", f"{s['caught']} blocked/stripped", "block_rate.md")
        add("leaked to the farmer", str(s["leaked"]), "block_rate.md")
        if blocks["meta"].get("llm_unavailable"):
            add("adversarial: LLM path", "not measured", "block_rate.md")
    return out


def step_summary(args) -> None:
    rows = rows_for_summary()
    if not rows:
        print("nothing to summarise — no artifacts on disk yet")
        return
    width = max(len(r[0]) for r in rows)
    print(f"\n{'metric'.ljust(width)}  {'value'.ljust(28)}  source")
    print(f"{'-' * width}  {'-' * 28}  {'-' * 24}")
    for label, value, source in rows:
        print(f"{label.ljust(width)}  {str(value).ljust(28)}  {source}")

    missing = [name for name in ("metrics.json", "lab_vs_field.json", "pipeline_scan.json",
                                 "block_rate.json", "latency.json") if not (ARTIFACTS / name).exists()]
    body = "\n".join(f"| {label} | {value} | `{source}` |" for label, value, source in rows)
    text = (
        "# Headline numbers\n\n"
        "Every row is read from an artifact on disk, not recomputed here. Rebuild with "
        "`ml/report/generate.py`.\n\n"
        f"| metric | value | source |\n|---|---|---|\n{body}\n"
    )
    if missing:
        text += f"\n_Not yet generated: {', '.join(missing)}._\n"
    (ARTIFACTS / "SUMMARY.md").write_text(text, encoding="utf-8")
    print(f"\nwrote {ARTIFACTS}/SUMMARY.md")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--only", nargs="+", choices=STEPS, help=f"run a subset of {', '.join(STEPS)}")
    p.add_argument("--skip", nargs="+", choices=STEPS, default=[])
    p.add_argument("--split", default="test")
    p.add_argument("--batch-size", type=int, default=64)
    p.add_argument("--num-workers", type=int, default=4)
    p.add_argument("--device", default="auto")
    p.add_argument("--online", action="store_true", help="also time the LLM drafting path")
    args = p.parse_args()

    steps = [s for s in (args.only or STEPS) if s not in args.skip]
    for name in steps:
        print(f"\n=== {name} ===")
        globals()[f"step_{name}"](args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
